[project]
name = "agents-knowledge"
version = "0.1.0"

dependencies = [
    "agents-core",
    "agents-intelligence",
    "integration-documentation",
    "integration-vectordb-qdrant",
    "langchain-text-splitters",
    "sentence-transformers",
]
