name: Test - Integration

on: [ push ]

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # we can't run docker on macos-latest. For more info read macos-docker.md
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache conda packages
        uses: actions/cache@v4
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: ${{ runner.os }}-conda-

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment.yml
          channels: conda-forge,defaults
          auto-activate-base: false
          activate-environment: agentic-knowledge-base
          conda-remove-defaults: true

      - name: Pull ollama image
        uses: ./.github/actions/docker-pull
        with:
          image_name: "ollama/ollama:0.13.0"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull test container image
        uses: ./.github/actions/docker-pull
        with:
          image_name: "testcontainers/ryuk:0.8.1"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull outline image
        uses: ./.github/actions/docker-pull
        with:
          image_name: "outlinewiki/outline:1.0"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull redis image
        uses: ./.github/actions/docker-pull
        with:
          image_name: "redis:7.4.7"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull postgres image
        uses: ./.github/actions/docker-pull
        with:
          image_name: "postgres:16.10"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run integration tests
        shell: bash -el {0}
        # `--capture=no` is not supported by pytest-xdist https://pytest-xdist.readthedocs.io/en/stable/
        # https://pytest-xdist.readthedocs.io/en/latest/known-limitations.html#output-stdout-and-stderr-from-workers
        run: uv sync; uv run pytest -v -l --tb=short -n auto -m "integration"

      - name: Docker images
        run: |
          docker images
