name: Test - Integration

on: [ push ]

jobs:
  integration:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # we can't run docker on macos-latest. For more info read macos-docker.md
        os: [ ubuntu-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment.yml
          channels: conda-forge,defaults
          auto-activate-base: false
          activate-environment: agentic-knowledge-base
          conda-remove-defaults: true

      - name: Docker images
        run: |
          docker images

      - name: Build and push Ollama Docker image
        uses: ./.github/actions/docker-build
        with:
          image_name: 'ollama/ollama:0.12.6'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker images
        run: |
          docker images

      - name: Run integration tests
        shell: bash -el {0}
        # `--capture=no` is equivalent to `-s`
        run: uv sync; uv run pytest -m "integration" --capture=no

      - name: Docker images
        run: |
          docker images
